services:
  - type: web
    name: eventpro-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: FRONTEND_URL
        value: "https://eventpro-frontend-eight.vercel.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://eventpro-frontend-eight.vercel.app,https://events-booking-7udo.vercel.app,https://event-bookings-git-main-ralphy-777s-projects.vercel.app,https://event-bookings-eosin.vercel.app,https://event-booking-chi.vercel.app,http://localhost:3000,http://127.0.0.1:3000"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://events-booking-ivpa.vercel.app,https://events-booking-7udo.vercel.app,https://event-bookings-git-main-ralphy-777s-projects.vercel.app,https://event-bookings-eosin.vercel.app,https://event-booking-chi.vercel.app,http://localhost:3000,http://127.0.0.1:3000"
      - key: DATABASE_URL
        fromDatabase:
          name: eventpro-db
          property: connectionString

databases:
  - name: eventpro-db
    databaseName: eventpro
    user: eventpro_user
