# Generated by Django 6.0.1 on 2026-03-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_booking_payment_method_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='user.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
