# Generated by Django 6.0.1 on 2026-03-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payment'),
    ]

    operations = [
    ]
