# Generated by Django 6.0.1 on 2026-03-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_video_remove_payment_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gcash_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
