# Generated by Django 6.0.1 on 2026-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_email_verified_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
