# Generated by Django 6.0.1 on 2026-03-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_booking_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='whole_day',
            field=models.BooleanField(default=False),
        ),
    ]
