# Generated by Django 6.0.1 on 2026-03-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_booking_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
