# Generated by Django 6.0.1 on 2026-03-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decline_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
