# Generated by Django 6.0.1 on 2026-03-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_booking_time_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPricing',
        ),
    ]
