# Generated by Django 6.0.3 on 2026-04-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_allow_booking_special_requests_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_types/'),
        ),
    ]
