# Generated by Django 6.0.3 on 2026-04-07 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_add_image_to_eventtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an image URL (use this on Render instead of uploading)', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='event_type',
            field=models.ForeignKey(blank=True, help_text='Select the event type this video belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='user.eventtype'),
        ),
    ]
